import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import "../public/scss/master.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { createClient } from "@/utils/supabase/server";

import { Header, Footer } from "@/components";
import { redirect } from "next/navigation";

const geistSans = Raleway({
  weight: ["100", "300", "400", "500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Evolvia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data, error } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Header user={data.user} />
        {children}
        <Footer />
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
